#! /bin/sh

_check() {
	[[ ! $(pidof -x $1) ]]
}

### AUTOSTART
_check sxhkd && sxhkd &
_check fusuma && fusuma &
picom -b


bspc monitor -d "1: " "2: " "3: " "4: " "5: " "6: " "7: " "8: " "9: " "0: "

bspc config top_padding		30
bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Screenkey manage=off

# External Rules
_check bspwm_external_rules && bspc config external_rules_command "$(command -v bspwm_external_rules)"


# rules for plasma desktop
bspc rule -a Plasma state=floating manage=off layer=normal
bspc rule -a plasmashell sticky=off layer=above state=floating focus=off 
